name: Build and Deploy APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build APK
        run: .\gradlew assembleDebug

      - name: Upload Bundle
        uses: actions/upload-artifact@v3
        with:
          name: test_app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: niraj07.k@gmail.com
          password: ${{ secrets.GMAIL_TOKEN }}
          subject: APK Build Notification
          body: |
            Here is the link to download the APK:
            ${{ steps.upload.outputs.artifact_url }}
          to: niraj.kumar@tissatech.com
